# Generated by Django 3.0.6 on 2020-05-11 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('customuser', '0002_auto_20200510_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_type',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
