# Generated by Django 3.0.6 on 2020-05-11 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_user_type_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_type',
            name='course',
        ),
    ]
