# Generated by Django 3.0.6 on 2020-05-12 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curricular_subject', '0002_curricular_subject_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='curricular_subject',
            name='teacher',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
