# Generated by Django 3.0.6 on 2020-05-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='curricular_subject',
        ),
        migrations.RemoveField(
            model_name='test',
            name='tested',
        ),
    ]
