# Generated by Django 3.0.6 on 2020-05-11 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curricular_subject', '0002_curricular_subject_course'),
        ('test', '0002_auto_20200511_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='curricular_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curricular_subject.curricular_subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='tested',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
